data:
  # File paths
  latest_path: "data/latest_draw.csv" 
  historical_path: "data/historical.csv"  # Required (format: MM/DD/YY,N1-N2-N3-N4-N5-N6)
  upcoming_path: " "      # Optional (same format as historical)
  stats_dir: "stats/"                    # Directory for analysis files
  results_dir: "results/"                # Directory for generated number sets
  
  # Upcoming draw handling
  merge_upcoming: true     # Whether to merge upcoming draws into historical data
  archive_upcoming: true   # Whether to create audit log of processed upcoming draws

validation:  # New section
  mode: "none"  # Options: "historical", "new_draw", "both", "none"
  test_draws: 300      # Number of past draws to test against
  alert_threshold: 4  # Minimum matches to trigger alerts
  save_report: true   # Generate validation.json
  sum_margin: 0.15          # ±15% of IQR
  check_hot_numbers: true

strategy:
  # Number pool configuration
  number_pool: 55          # Total numbers in the lottery (1-55)
  numbers_to_select: 6     # Numbers to pick per set
  
  # Weight distribution (must sum to 1.0)
  frequency_weight: 0.45    # Historical frequency importance (40%)
  recent_weight: 0.5       # Recent appearances importance (20%)
  random_weight: 0.05       # Pure randomness component (40%)
  
  # Strategic rules
  low_number_max: 10       # Numbers ≤10 are considered "low"
  low_number_chance: 0.7   # 70% chance to include ≥1 low number
  high_prime_min: 35       # Primes >35 are "high primes"
  high_prime_chance: 0.25  # 25% chance to include 1 high prime
  
  # Cold number handling
  cold_threshold: 30       # Number of past draws to check for cold numbers
  resurgence_threshold: 2  # Appearances needed to exit "cold" status

output:
  sets_to_generate: 5     # Number of sets to produce
  save_analysis: true      # Whether to save statistical reports
  verbose: false           # Whether to show detailed processing info
  high_low:
    decimal_places: 1
    show_combo_stats: true
  max_attempts: 100         # Safety limit
  debug: false  
  sum_percentiles: true

analysis:
  hot_boost: 1.2       # +20% weight for hot numbers
  cold_penalty: 0.8    # -20% weight for cold numbers
  default_match_threshold: 4    # Fallback when CLI not provided
  default_show_top: 5           # Fallback when CLI not provided
  min_display_matches: 1        # Hide single matches if needed
  recency_units: draws  # "draws" or "days"
  recency_bins:
    hot: 15    # Recent threshold
    warm: 30   # Semi-recent
    cold: 31   # Beginning of "cold" range
  show_combined_stats: true

  gap_analysis:
    # Core Functionality
    enabled: true               # Enable/disable gap analysis
    mode: "auto"                # "auto" (dynamic thresholds) or "manual" (fixed)
    analyze_adjacent_only: true # Only track gaps between consecutive numbers

    # Data Scope
    lookback_draws: 500         # Analyze last 500 draws (adjust for your lottery's volatility)
    min_gap_size: 1             # Minimum gap to track (e.g., 1 for [3,4])
    max_gap_size: 20            # Maximum gap to track (e.g., ignore [1,99] in 6/55 games)

    # Frequency Filters
    min_frequency: 5            # Ignore gaps appearing <5 times in history

    # Thresholds
    auto_threshold: 1.5         # Flag gaps unseen for 1.5x their historical avg
    manual_threshold: 10        # If mode="manual", flag gaps unseen for 10+ draws

    # Strategy Integration
    weight_influence: 0.3       # How much gaps influence number generation (0=ignore, 1=strict)
    alert_level: "warn"         # "warn" (log only) or "reject" (discard invalid sets)

    # Advanced
    track_consecutive: true     # Track clusters of small gaps (e.g., [3,5,7] → gaps [2,2])

  overdue_analysis:
    enabled: true
    mode: auto               # or "manual"
    auto_threshold: 1.5      # (avg_gap * 1.5 = overdue)
    manual_threshold: 10     # Fixed draw count (if mode: manual)
    weight_influence: 0.3    # How much gaps affect set generation (0-1)
    min_avg_gap: 5           # Ignore frequent numbers
    trend_lookback: 10    # For trend analysis
    bin_size: 5           # For distribution charts
    acceleration_threshold: 0.5

  combined_stats_settings:
    min_overlap_significance: 0.5
    freq_cutoff: 20  # Top 20 considered "frequent"
  top_range: 5
  combination_analysis:
    pairs: true
    triplets: true
    quadruplets: true
    quintuplets: true
    sixtuplets: true 
  min_combination_count: 2
  frequency:
    draws: 1000 
    min_display: 3
  primes:
    enabled: true 
    draws: 500
    hot_threshold: 5
    prime_weight: 1.2     
  high_low:
    draws: 400          # Middle ground in 300-500 range
    recency_weight: 0.3
    low_number_max: 10 
    enable_ratio_analysis: true
    alert_threshold: 0.15
  number_ranges:
    low_max: 15      # 1-15 = Low
    mid_max: 30      # 16-30 = Mid 
    high_max: 45     # 31-45 = High (or 58 for bigger pools)
    # Optional:
    dynamic_ranges: true  # Auto-adjust based on number_pool
    
    ########### Future Sections #########
    
  patterns:  # New umbrella section
    enabled: true  # Master switch
    alert_level: "warn"  # none|warn|reject
    
    odd_even:  # New explicit control
      enabled: true
      ideal_range: [30, 70]  # Min-max % of even numbers
      strict: false  # If true, rejects all-even/odd sets
    
      weight_penalty: 0.9 # 10% penalty for odds  
      weight_boost: 1.1   # 10% boost for evens  
    
    # Keep existing pattern settings (they'll still work)
    consecutive_weight: 0.3 
    same_last_digit_weight: 0.2
    prime_weight: 0.1
    
    #####################################
 # Add these new sections (keep existing ones)
mode: auto  # New root-level option

auto:  # New section
  learning_rate: 0.01
  decay_factor: 0.97

manual:  # New section
  strategy:
    weighting:
      frequency: 0.4
      recency: 0.3
      randomness: 0.3
      resurgence: 0.1
    presets:
      balanced: [0.4, 0.3, 0.2, 0.1]
      anti_pattern: [0.1, 0.1, 0.8, 0.3]

features:
  enable_pattern_analysis: true  # Off by default
  enable_combo_stats: true      # Off by default

pattern_settings:
  consecutive_weight: 0.3
  same_last_digit_weight: 0.2
  prime_weight: 0.1